name: flutter_incoming_request
description: A Flutter package for displaying incoming requests (like CallKit) with deep linking and custom UI.
version: 1.0.0
homepage: https://github.com/kashyapsandesh/flutter_incoming_request

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.kashyapsandesh.flutter_incoming_request
        pluginClass: FlutterIncomingRequestPlugin
      ios:
        pluginClass: FlutterIncomingRequestPlugin
